fix missing mandatory flag on API 31+
java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above)
requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>